#!/usr/bin/env python3
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.1.0pre on Fri Jun 17 17:09:56 2022 for Atsro Linux
# last changed Do 14 Mär 2024 17:45:14 CET for KidsLinux my Michael John
#

import wx

# begin wxGlade: dependencies
import gettext
# end wxGlade

# begin wxGlade: extracode
import webbrowser
import subprocess
import os, sys
# end wxGlade

class MyDialog(wx.Dialog): 
   def __init__(self, parent, title): 
      super(MyDialog, self).__init__(parent, title = title, size = (350, 480)) 
      panel = wx.Panel(self) 
      self.SetClientSize(size = (350,480))
      self.button_CLOSE = wx.Button(panel, wx.ID_CLOSE, label = "Close", size = (75, 32), pos = (75, 440))
      self.button_CLOSE.Center(dir=wx.HORIZONTAL)
      #self.button_CLOSE.SetMinSize(wx.DLG_UNIT(self.button_CLOSE, wx.Size(75, 32)))
      self.SetEscapeId(self.button_CLOSE.GetId())
      _icon = wx.NullIcon
      _icon.CopyFromBitmap(wx.Bitmap("/usr/share/pixmaps/kidslinux-logo.png", wx.BITMAP_TYPE_ANY))
      self.SetIcon(_icon)

class Welcome(wx.Dialog):
    def __init__(self, *args, **kwds):
        # begin wxGlade: Welcome.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_DIALOG_STYLE
        wx.Dialog.__init__(self, *args, **kwds)
        self.SetSize((640, 480))
        self.SetTitle(_("Welcome to KidsLinux"))
        _icon = wx.NullIcon
        _icon.CopyFromBitmap(wx.Bitmap("/usr/share/pixmaps/kidslinux-logo.png", wx.BITMAP_TYPE_ANY))
        self.SetIcon(_icon)

        sizer_1 = wx.BoxSizer(wx.VERTICAL)

        sizer_3 = wx.BoxSizer(wx.VERTICAL)
        sizer_1.Add(sizer_3, 1, wx.ALL | wx.EXPAND, 10)

        label_1 = wx.StaticText(self, wx.ID_ANY, _("KidsLinux 24.03 \"Vienna\""), style=wx.ALIGN_CENTER_HORIZONTAL)
        sizer_3.Add(label_1, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        sizer_3.Add((20, 20), 0, 0, 0)

        bitmap_1 = wx.StaticBitmap(self, wx.ID_ANY, wx.Bitmap("/usr/share/pixmaps/kidslinux-logo-128px.png", wx.BITMAP_TYPE_ANY))
        bitmap_1.SetMinSize((128, 128))
        bitmap_1.SetMaxSize((128, 128))
        sizer_3.Add(bitmap_1, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.ALL, 0)

        sizer_3.Add((20, 20), 0, 0, 0)

        label_2 = wx.StaticText(self, wx.ID_ANY, _("Welcome to KidsLinux!"))
        label_2.SetFont(wx.Font(14, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, ""))
        sizer_3.Add(label_2, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        sizer_3.Add((20, 10), 0, 0, 0)

        label_3 = wx.StaticText(self, wx.ID_ANY, _("*KidsLinux* is a Linux distribution based on Arch Linux, focusing on child education and games.\nNow, you may use the buttons below to get further information."))
        label_3.Wrap(600)
        sizer_3.Add(label_3, 0, wx.EXPAND, 0)

        sizer_3.Add((20, 20), 0, 0, 0)

        grid_sizer_1 = wx.GridBagSizer(5, 5)
        sizer_3.Add(grid_sizer_1, 1, wx.EXPAND, 0)

        self.button_1 = wx.Button(self, wx.ID_ANY, _("Visit kidslinux.org"))
        self.button_1.SetMinSize(wx.DLG_UNIT(self.button_1, wx.Size(75, 14)))
        grid_sizer_1.Add(self.button_1, (0, 0), (1, 1), 0, 0)

        self.button_2 = wx.Button(self, wx.ID_ANY, _("KidsLinux Programs"))
        self.button_2.SetMinSize(wx.DLG_UNIT(self.button_2, wx.Size(75, 14)))
        grid_sizer_1.Add(self.button_2, (0, 1), (1, 1), 0, 0)

        self.button_3 = wx.Button(self, wx.ID_ANY, _("Package Manager"))
        self.button_3.SetMinSize(wx.DLG_UNIT(self.button_3, wx.Size(75, 14)))
        grid_sizer_1.Add(self.button_3, (0, 2), (1, 1), 0, 0)

        self.button_4 = wx.Button(self, wx.ID_ANY, _("System Settings"))
        self.button_4.SetMinSize(wx.DLG_UNIT(self.button_4, wx.Size(75, 14)))
        grid_sizer_1.Add(self.button_4, (0, 3), (1, 1), 0, 0)

        self.button_5 = wx.Button(self, wx.ID_ANY, _("Visit the KidsLinux Wiki"))
        self.button_5.SetMinSize(wx.DLG_UNIT(self.button_5, wx.Size(75, 14)))
        grid_sizer_1.Add(self.button_5, (1, 0), (1, 1), 0, 0)

        self.button_6 = wx.Button(self, wx.ID_ANY, _("Contributing to KidsLinux"))
        self.button_6.SetMinSize(wx.DLG_UNIT(self.button_6, wx.Size(75, 14)))
        grid_sizer_1.Add(self.button_6, (1, 1), (1, 1), 0, 0)

        self.button_7 = wx.Button(self, wx.ID_ANY, _("Copyright notices"))
        self.button_7.SetMinSize(wx.DLG_UNIT(self.button_7, wx.Size(75, 14)))
        grid_sizer_1.Add(self.button_7, (1, 2), (1, 1), 0, 0)

        self.button_8 = wx.Button(self, wx.ID_ANY, _("Send Feedback"))
        self.button_8.SetMinSize(wx.DLG_UNIT(self.button_8, wx.Size(75, 14)))
        grid_sizer_1.Add(self.button_8, (1, 3), (1, 1), 0, 0)

        sizer_2 = wx.StdDialogButtonSizer()
        sizer_1.Add(sizer_2, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.ALL, 5)

        self.button_CLOSE = wx.Button(self, wx.ID_CLOSE, "")
        self.button_CLOSE.SetMinSize(wx.DLG_UNIT(self.button_CLOSE, wx.Size(75, 14)))
        sizer_2.AddButton(self.button_CLOSE)

        self.button_HELP = wx.Button(self, wx.ID_HELP, "")
        self.button_HELP.SetMinSize(wx.DLG_UNIT(self.button_HELP, wx.Size(75, 14)))
        sizer_2.AddButton(self.button_HELP)

        self.checkbox_1 = wx.CheckBox(self, wx.ID_ANY, _("Autostart \"Welcome\""))
        self.checkbox_1.SetValue(1)
        sizer_2.Add(self.checkbox_1, 0, wx.EXPAND, 0)

        sizer_2.Realize()

        self.SetSizer(sizer_1)

        self.SetEscapeId(self.button_CLOSE.GetId())

        self.Layout()

        self.button_1.Bind(wx.EVT_BUTTON, self.btn1_Click)
        self.button_2.Bind(wx.EVT_BUTTON, self.btn2_Click)
        self.button_3.Bind(wx.EVT_BUTTON, self.btn3_Click)
        self.button_4.Bind(wx.EVT_BUTTON, self.btn4_Click)
        self.button_5.Bind(wx.EVT_BUTTON, self.btn5_Click)
        self.button_6.Bind(wx.EVT_BUTTON, self.btn6_Click)
        self.button_7.Bind(wx.EVT_BUTTON, self.btn7_Click)
        self.button_8.Bind(wx.EVT_BUTTON, self.btn8_Click)
        self.button_HELP.Bind(wx.EVT_BUTTON, self.btnHelp_Click)
        self.checkbox_1.Bind(wx.EVT_CHECKBOX, self.chkAutostart_Clicked)
        # end wxGlade

    def btn1_Click(self, event):  # wxGlade: Welcome.<event_handler>
        url = 'https://kidslinux.org/'
        webbrowser.open(url)
        event.Skip()

    def btn2_Click(self, event):  # wxGlade: Welcome.<event_handler>
        a = MyDialog(self, "KidsLinux Programs").ShowModal() 
        event.Skip()

    def btn3_Click(self, event):  # wxGlade: Welcome.<event_handler>
        subprocess.run("pamac-manager")
        event.Skip()

    def btn4_Click(self, event):  # wxGlade: Welcome.<event_handler>
        subprocess.run("xfce4-settings-manager")
        event.Skip()

    def btn5_Click(self, event):  # wxGlade: Welcome.<event_handler>
        url = 'https://wiki.kidslinux.org/'
        webbrowser.open(url)
        event.Skip()

    def btn6_Click(self, event):  # wxGlade: Welcome.<event_handler>
        a = MyDialog(self, "Contributing to KidsLinux").ShowModal() 
        event.Skip()

    def btn7_Click(self, event):  # wxGlade: Welcome.<event_handler>
        a = MyDialog(self, "Copyright notices").ShowModal() 
        event.Skip()

    def btn8_Click(self, event):  # wxGlade: Welcome.<event_handler>
        subprocess.run(["xdg-open", "mailto:kidslinux@kidslinux.org?subject=KidsLinux Feedback"])
        event.Skip()

    def btnHelp_Click(self, event):  # wxGlade: Welcome.<event_handler>
        print("Event handler 'btnHelp_Click' not implemented!")
        event.Skip()

    def chkAutostart_Clicked(self, event):  # wxGlade: Welcome.<event_handler>
        print("Event handler 'chkAutostart_Clicked' not implemented!")
        event.Skip()

# end of class Welcome

class MyApp(wx.App):
    def OnInit(self):
        self.dialog = Welcome(None, wx.ID_ANY, "")
        self.SetTopWindow(self.dialog)
        self.dialog.ShowModal()
        self.dialog.Destroy()
        return True

# end of class MyApp

if __name__ == "__main__":
    gettext = gettext.translation('astrolinux-welcome-app')
    # not needed: localedir='locale'
    # not needed: gettext.install("astrolinux-welcome-app")
    _ = gettext.gettext

    app = MyApp(0)
    app.MainLoop()
